apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: buildfarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - args:
        - -scheduler=ubuntu16-04|scheduler-ubuntu16-04:8981
        image: remoteapistesting/bb-storage:latest
        name: storage
        ports:
        - containerPort: 8980
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: config-storage-clients
        name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: frontend
  namespace: buildfarm
spec:
  ports:
  - port: 8980
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
