apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: buildfarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  serviceName: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - args:
        - -allow-ac-updates-for-instance=ubuntu16-04
        image: remoteapistesting/bb-storage:61175361
        name: storage
        ports:
        - containerPort: 8980
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /cas
          name: cas
        - mountPath: /ac
          name: ac
      volumes:
      - configMap:
          name: config-storage
        name: config
  volumeClaimTemplates:
  - metadata:
      name: cas
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 12Gi
  - metadata:
      name: ac
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: storage
  namespace: buildfarm
spec:
  clusterIP: None
  ports:
  - port: 8980
    protocol: TCP
  selector:
    app: storage
---
apiVersion: v1
data:
  blobstore.conf: |
    content_addressable_storage {
      circular {
        directory: "/cas"
        offset_file_size_bytes: 16777216           # 16 MiB
        offset_cache_size: 10000
        data_file_size_bytes: 10737418240          # 10 GiB
        data_allocation_chunk_size_bytes: 16777216 # 16 MiB
        # Blobs for all instances are stored in a single CAS.
      }
    }
    action_cache {
      circular {
        directory: "/ac"
        offset_file_size_bytes: 1048576           # 1 MiB
        offset_cache_size: 1000
        data_file_size_bytes: 104857600           # 100 MiB
        data_allocation_chunk_size_bytes: 1048576 # 1 MiB
        # List of instances for which to create an AC.
        instance: "ubuntu16-04"
      }
    }
kind: ConfigMap
metadata:
  name: config-storage
  namespace: buildfarm
