ansible_python_interpreter: "/usr/bin/python3"

# Bazel remote exeuction config

# address of the remote executor, for buildbarn this is 8980
bazel_re_addr: "localhost"
bazel_remote_executor: "{{ bazel_re_addr }}:8980"

# Instance name, for buildbarn the default is 'local', for buildgrid it is 'main'
bazel_instance_name: "local"

# Tensorflow config
# Build directory
tf_build_dir: "$HOME/tensorflow"

# Docker sha digest of the container to be used
tf_digest: "5fa2ec44cdc3bc952fd86bddf02dac3eb83f885659c9bbf7319cc22525bf99cb"

# Branch of the tensorflow source code to be used
tf_branch: "r1.13"

# Specific sha of the tensorflow source code to be used (in the branch specified above)
tf_src_sha: "073471cd2c2c27feb930618c5692c75549a406c8"
