- name: get base dependencies
  apt:
    name:
      - python2.7
  become: yes

- name: "Setup udev rules"
  copy:
      src: ebs_udev
      dest: "/etc/udev/rules.d/80-aws-ebs.rules"
  become: yes

- name: "Install ebsnvme-id"
  copy:
      src: ebsnvme-id
      dest: "/sbin/ebsnvme-id"
      mode: "a+x"
  become: yes

- name: "Mount cache volume"
  mount:
    path: "{{ cache_mount_point }}"
    src: "{{ nvme_mount }}"
    fstype: ext4
    state: present
    opts: defaults,nofail
    passno: 2
  become: yes

- name: Reboot
  reboot:
    reboot_timeout: 600
  become: yes