#!/bin/bash

# First argument is the git repo to build with Bazel
git_repo=$1
# All the remaining arguments will be passed to `bazel build`
bazel_args="${@:2}"

echo "## bazelrc file:"
cat bazelrc
echo "## end of bazelrc"

git clone $git_repo repo

cd repo

# Append toolchain to the workspace
sed -i -e 's/\(bazel_toolchains\)/\1_old/' WORKSPACE
cat /src/workspace >> WORKSPACE


echo "## WORKSPACE file:"
cat WORKSPACE
echo "## end of WORKSPACE"

# Execute bazel build
set -x
/root/.bazel/bin/bazel --bazelrc=/src/bazelrc build $bazel_args
