#!/bin/bash

# First argument is the git repo to build with Bazel
git_repo=$1
# All the remaining arguments will be passed to `bazel build`
bazel_args="${@:2}"

echo "## bazelrc file:"
cat bazelrc
echo "## end of bazelrc"

git clone $git_repo repo

cd repo

# Append toolchain to the workspace
cat /src/workspace >> WORKSPACE

# Execute bazel build
set -x
bazel --bazelrc=/src/bazelrc build $bazel_args
