- name: download go
  get_url:
    url: "{{ go_release_url }}"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: 0755

- name: install go
  unarchive:
      src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
      dest: "{{ go_install_path }}/"
      remote_src: "yes"
  become: yes

- name: export goroot
  shell: "export GOPATH={{ go_install_path }}/go"

- name: update path
  shell: "export PATH=$GOPATH/bin:$PATH"