apiVersion: v1
data:
  frontend.json: |
    {
      "blobstore": {
        "contentAddressableStorage": {
          "grpc": {
            "endpoint": "storage-0.storage:8980"
          }
        },
        "actionCache": {
          "grpc": {
            "endpoint": "storage-0.storage:8980"
          }
        }
      },
      "schedulers": {
        "ubuntu16-04": "scheduler-ubuntu16-04:8981"
      }
    }
kind: ConfigMap
metadata:
  name: frontend
  namespace: buildbarn