apiVersion: v1
data:
  storage.json: |
    {
      "blobstore": {
        "contentAddressableStorage": {
          "cloud": {
            "keyPrefix": "cas/",
            "url": "mem://"
          }
        },
        "actionCache": {
          "cloud": {
            "keyPrefix": "ac/",
            "url": "mem://"
          }
        }
      },
      "allowAcUpdatesForInstances": ["ubuntu16-04"]
    }
kind: ConfigMap
metadata:
  name: storage
  namespace: buildbarn