apiVersion: v1
data:
  storage.json: |
    {
      "blobstore": {
        "contentAddressableStorage": {
          "circular": {
            "directory": "/cas",
            "offsetFileSizeBytes": 16777216,
            "offsetCacheSize": 10000,
            "dataFileSizeBytes": 10737418240,
            "dataAllocationChunkSizeBytes": 16777216
          }
        },
        "actionCache": {
          "circular": {
            "directory": "/ac",
            "offsetFileSizeBytes": 1048576,
            "offsetCacheSize": 1000,
            "dataFileSizeBytes": 104857600,
            "dataAllocationChunkSizeBytes": 1048576,
            "instance": ["ubuntu16-04"]
          }
        }
      },
      "allowAcUpdatesForInstances": ["ubuntu16-04"]
    }
kind: ConfigMap
metadata:
  name: storage
  namespace: buildbarn