apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler-ubuntu16-04
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
      instance: ubuntu16-04
  template:
    metadata:
      labels:
        app: scheduler
        instance: ubuntu16-04
    spec:
      containers:
      - args:
        - /config/scheduler.json
        image: remoteapistesting/bb-scheduler:latest
        name: scheduler
        ports:
        - containerPort: 8981
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: scheduler
        name: config
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-ubuntu16-04
  namespace: buildbarn
spec:
  ports:
  - port: 8981
    protocol: TCP
  selector:
    app: scheduler
    instance: ubuntu16-04
  type: ClusterIP