apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-ubuntu16-04
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      instance: ubuntu16-04
  template:
    metadata:
      labels:
        app: worker
        instance: ubuntu16-04
    spec:
      containers:
      - args:
        - /config/worker.json
        image: remoteapistesting/bb-worker:latest
        name: worker
        volumeMounts:
        - mountPath: /config
          name: config-worker
        - mountPath: /worker
          name: worker
      - args:
        - /config/runner.json
        image: remoteapistesting/bb-runner-ubuntu16-04:latest
        name: runner
        volumeMounts:
        - mountPath: /config
          name: config-runner
        - mountPath: /worker
          name: worker
      initContainers:
      - name: volume-init
        image: busybox:1.30.1
        command:
        - sh
        - -c
        - mkdir -pm 0777 /worker/build && mkdir -pm 0700 /worker/cache && chmod 0777 /worker
        volumeMounts:
        - mountPath: /worker
          name: worker
      volumes:
      - configMap:
          name: worker
        name: config-worker
      - emptyDir: {}
        name: worker
      - configMap:
          name: runner
        name: config-runner