#!/bin/bash

# First argument is the git repo to build with Bazel
git_repo=$1
# All the remaining arguments will be passed to `bazel build`
bazel_args="${@:2}"
bazel_target="${@: -1}"

echo "## bazelrc file:"
cat bazelrc
echo "## end of bazelrc\n"

git clone $git_repo repo
cd repo

# Rename bazel_toolchains if present
sed -i -e 's/"bazel_toolchains"/"bazel_toolchains_old"/' WORKSPACE
# Append toolchain to the workspace
cat /src/workspace >> WORKSPACE

echo "## WORKSPACE file:"
cat WORKSPACE
echo "## end of WORKSPACE\n"

# Execute bazel build
set -x

echo "Attempting to fetch target:"
echo $bazel_target

for i in {0..10}
    do
        bazel fetch $bazel_target && break
    done

bazel --bazelrc=/src/bazelrc build $bazel_args
